config/routes.rb
Rails.application.routes.draw do

  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show, :destroy]
    get 'dashboard', to: 'dashboard#index'
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'site/home#index'
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :member
  belongs_to :category
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :description
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller? && resource_name == :admin
      "backoffice_devise"
    else
      "application"
    end
  end
end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update]

  def index
    @admins = Admin.all
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to backoffice_admins_path, notice: "O administrador (#{@admin.email}) foi cadastrado!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    password = params[:admin][:password]
    password_confirmation = params[:admin][:password_confirmation]

    if password.blank? && password_confirmation.blank?
      params[:admin].delete(:password)
      params[:admin].delete(:password_confirmation)
    end

    if @admin.update(params_admin)
      redirect_to backoffice_admins_path, notice: "Dados do administrador (#{@admin.email}) atualizados!"
    else
      render :edit
    end
  end

  private

    def set_admin
      @admin = Admin.find(params[:id])
    end

    def params_admin
      params.require(:admin).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only: [:edit, :update]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params_category)
    if @category.save
      redirect_to backoffice_categories_path, notice: "Categoria cadastrada!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(params_category)
      redirect_to backoffice_categories_path, notice: "Categoria atualizada!"
    else
      render :edit
    end
  end

  private

    def set_category
      @category = Category.find(params[:id])
    end

    def params_category
      params.require(:category).permit(:description)
    end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController

  def index
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ActionController::Base
  
  before_action :authenticate_admin!

  layout 'backoffice'

end

app/controllers/site/home_controller.rb
class Site::HomeController < ApplicationController
  layout 'site'

  def index
    @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/backoffice/admins/edit.html.erb
<%= render :partial => "backoffice/admins/shared/form", locals: { action: "Editar Admin" } %>

app/views/backoffice/admins/index.html.1.erb
<!-- Breadcrumbs-->
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <%= link_to  "Dashboard", backoffice_path %>
  </li>
  <li class="breadcrumb-item active">Admins Page</li>
</ol>

<div class="col-sm-10 offset-1">
  <div class="card mt-5 mb-5">
    <div class="card-header">
      Administadores
    <%= link_to new_backoffice_category_path, class: "btn btn-success float-right" do %>
      <i class="fa fa-edit"></i> Nova
    <% end %>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table">
          <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Descrição</th>
                <th scope="col">Atualizado Em</th>
                <th scope="col">Criado Em</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              <% @categories.each do |category| %>
              <tr>
                <th scope="row"><%= category.id %></th>
                <td><%= category.description %></td>
                <td><%= category.updated_at %></td>
                <td><%= category.created_at %></td>
                <td>
                  <div class="btn-group" role="group">
                  <%= link_to edit_backoffice_category_path(category), class: "btn btn-primary" do %>
                    <i class="fa fa-edit"></i> Editar
                  <% end %>
                    <button type="button" class="btn btn-danger disabled">Delete</button>
                  </div>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/backoffice/admins/index.html.erb
<!-- Breadcrumbs-->
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <%= link_to  "Dashboard", backoffice_path %>
  </li>
  <li class="breadcrumb-item active">Admins Page</li>
</ol>

<div class="col-sm-10 offset-1">
  <div class="card mt-5 mb-5">
    <div class="card-header">
      Administadores
    <%= link_to new_backoffice_admin_path, class: "btn btn-success float-right" do %>
      <i class="fa fa-edit"></i> Nova
    <% end %>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table">
          <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Email</th>
                <th scope="col">Atualizado Em</th>
                <th scope="col">Criado Em</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              <% @admins.each do |admin| %>
              <tr>
                <th scope="row"><%= admin.id %></th>
                <td><%= admin.email %></td>
                <td><%= admin.updated_at %></td>
                <td><%= admin.created_at %></td>
                <td>
                  <div class="btn-group" role="group">
                  <%= link_to edit_backoffice_admin_path(admin), class: "btn btn-primary" do %>
                    <i class="fa fa-edit"></i> Editar
                  <% end %>
                    <button type="button" class="btn btn-danger disabled">Delete</button>
                  </div>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/backoffice/admins/new.html.erb
<%= render :partial => "backoffice/admins/shared/form", locals: { action: "Novo administrador" } %>

app/views/backoffice/admins/shared/_form.html.erb
<!-- Breadcrumbs-->
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <%= link_to  "Dashboard", backoffice_path %>
  </li>
  <li class="breadcrumb-item">
    <%= link_to  "Administradores", backoffice_admins_path %>
  </li>
  <li class="breadcrumb-item active"><%= action %></li>
</ol>

<div class="col-sm-10 offset-1">
  <% if @admin.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @admin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card mt-5 mb-5">
    <div class="card-header"><%= action %></div>
      <div class="card-body">
        <div class="col-lg-8">
          <%= form_for([:backoffice, @admin]) do |f| %>
            <div class="form-group">
              <div class="form-label-group">
                <%= f.text_field :email, id:"email", class:"form-control", placeholder:"Ex.: seunome@aomercado.com", required:"required", autofocus:"autofocus" %>
                <label for="email">Email do Administrador</label>
              </div>
            </div>
            <div class="form-group">
              <div class="form-label-group">
                <%= f.password_field :password, id:"password", class:"form-control", placeholder:"Senha", required:"required", autofocus:"autofocus" %>
                <label for="password">Senha</label>
              </div>
            </div>
            <div class="form-group">
              <div class="form-label-group">
                <%= f.password_field :password_confirmation, id:"password_confirmation", class:"form-control", placeholder:"Confirmação da senha", required:"required", autofocus:"autofocus" %>
                <label for="password_confirmation">Confirmação da senha</label>
              </div>
            </div>
            
            <button type="submit" class="btn btn-primary">Cadastrar</button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/backoffice/categories/edit.html.erb
<%= render :partial => "backoffice/categories/shared/form", locals: { action: "Editar Categoria" } %>

app/views/backoffice/categories/index.html.erb
<!-- Breadcrumbs-->
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <%= link_to  "Dashboard", backoffice_path %>
  </li>
  <li class="breadcrumb-item active">Categories Page</li>
</ol>
<h1>Backoffice::Categories#index</h1>

<div class="col-sm-10 offset-1">
  <div class="card mt-5 mb-5">
    <div class="card-header">
      Categorias
    <%= link_to new_backoffice_category_path, class: "btn btn-success float-right" do %>
      <i class="fa fa-edit"></i> Novo
    <% end %>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table">
          <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Descrição</th>
                <th scope="col">Atualizado Em</th>
                <th scope="col">Criado Em</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              <% @categories.each do |category| %>
              <tr>
                <th scope="row"><%= category.id %></th>
                <td><%= category.description %></td>
                <td><%= category.updated_at %></td>
                <td><%= category.created_at %></td>
                <td>
                  <div class="btn-group" role="group">
                  <%= link_to edit_backoffice_category_path(category), class: "btn btn-primary" do %>
                    <i class="fa fa-edit"></i> Editar
                  <% end %>
                    <button type="button" class="btn btn-danger disabled">Delete</button>
                  </div>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/backoffice/categories/new.html.erb
<%= render :partial => "backoffice/categories/shared/form", locals: { action: "Editar Categoria" } %>

app/views/backoffice/dashboard/index.html.erb
<!-- Breadcrumbs-->
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="index.html">Dashboard</a>
  </li>
  <li class="breadcrumb-item active">Blank Page</li>
</ol>

<div class="row">
  <div class="col-xl-3 col-sm-6 mb-3">
    <div class="card text-white bg-primary o-hidden h-100">
      <div class="card-body">
        <div class="card-body-icon">
          <i class="fas fa-fw fa-comments"></i>
        </div>
        <div class="mr-5">26 New Messages!</div>
      </div>
      <a class="card-footer text-white clearfix small z-1" href="#">
        <span class="float-left">View Details</span>
        <span class="float-right">
          <i class="fas fa-angle-right"></i>
        </span>
      </a>
    </div>
  </div>
  <div class="col-xl-3 col-sm-6 mb-3">
    <div class="card text-white bg-warning o-hidden h-100">
      <div class="card-body">
        <div class="card-body-icon">
          <i class="fas fa-fw fa-list"></i>
        </div>
        <div class="mr-5">11 New Tasks!</div>
      </div>
      <a class="card-footer text-white clearfix small z-1" href="#">
        <span class="float-left">View Details</span>
        <span class="float-right">
          <i class="fas fa-angle-right"></i>
        </span>
      </a>
    </div>
  </div>
  <div class="col-xl-3 col-sm-6 mb-3">
    <div class="card text-white bg-success o-hidden h-100">
      <div class="card-body">
        <div class="card-body-icon">
          <i class="fas fa-fw fa-shopping-cart"></i>
        </div>
        <div class="mr-5">123 New Orders!</div>
      </div>
      <a class="card-footer text-white clearfix small z-1" href="#">
        <span class="float-left">View Details</span>
        <span class="float-right">
          <i class="fas fa-angle-right"></i>
        </span>
      </a>
    </div>
  </div>
  <div class="col-xl-3 col-sm-6 mb-3">
    <div class="card text-white bg-danger o-hidden h-100">
      <div class="card-body">
        <div class="card-body-icon">
          <i class="fas fa-fw fa-life-ring"></i>
        </div>
        <div class="mr-5">13 New Tickets!</div>
      </div>
      <a class="card-footer text-white clearfix small z-1" href="#">
        <span class="float-left">View Details</span>
        <span class="float-right">
          <i class="fas fa-angle-right"></i>
        </span>
      </a>
    </div>
  </div>
</div>
</div>

<div class="container">
  <!-- Page Content -->
  <h1>Blank Page</h1>
  <h2>Olá <%= current_admin.email %> teu IP: <%= current_admin.current_sign_in_ip %></h2>
  <hr>
  <p>This is a great starting point for new custom pages.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AomercadoWeb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/backoffice.html.erb
<!DOCTYPE html>
<html lang="pt-PT">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">

    <title>aoMercado | BackOffice</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="description" content="Mini loja virtual, um projecto do curso completo de Ruby on Rails">
    <meta name="keywords" content="mercado, virtual, online, compras, pagamentos, loja, e-commerce"/>
    <meta name="robots" content="index, follow">
    <meta name="author" content="Nelson Mfinda">
    <meta name="theme-color" content="#FFFFFF">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'backoffice', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'backoffice', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= render partial: "layouts/backoffice_shared/topbar" %>

    <div id="wrapper">
      <!-- Sidebar -->
      <%= render partial: "layouts/backoffice_shared/sidebar" %>

      <div id="content-wrapper">

        <div class="container-fluid">
          <%= yield %>
        </div>
        <!-- /.container-fluid -->

        <!-- Sticky Footer -->
        <%= render partial: "layouts/backoffice_shared/footer" %>
      </div>
      <!-- /.content-wrapper -->

      <!-- Scroll to Top Button-->
      <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
      </a>
    </div>
    <!-- /#wrapper -->

      <% if notice %>
        <script>
          $.notify("<%= notice %>", "success");
        </script>
      <% end %>
  </body>
</html>

app/views/layouts/backoffice_devise.html.erb
<!DOCTYPE html>
<html lang="pt-PT">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">

  <title>aoMercado | BackOffice - Login</title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="description" content="Mini loja virtual, um projecto do curso completo de Ruby on Rails">
  <meta name="keywords" content="mercado, virtual, online, compras, pagamentos, loja, e-commerce"/>
  <meta name="robots" content="index, follow">
  <meta name="author" content="Nelson Mfinda">
  <meta name="theme-color" content="#FFFFFF">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    'backoffice', media: 'all', 'data-turbolinks-track': 'reload' %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'backoffice', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div class="container">
    <div class="col-md-8 text-center offset-2 mt-xl-5">
      <h1>AoMercado - Fazer compras<br /> no mercado, tornou-se mais fácil.</h1>
    </div>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/backoffice_shared/_footer.html.erb
<footer class="sticky-footer">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright © aoMercado 2019</span>
    </div>
  </div>
</footer>

app/views/layouts/backoffice_shared/_sidebar.html.erb
<!-- Sidebar -->
<ul class="sidebar navbar-nav">
  <li class="nav-item">
  <%= link_to backoffice_path, class: "nav-link" do %>
    <i class="fas fa-fw fa-tachometer-alt"></i>
    <span>Dashboard</span>
  <% end %>
  </li>
  <li class="nav-item">
  <%= link_to backoffice_categories_path, class: "nav-link" do %>
    <i class="fas fa-fw fa-chart-area"></i>
    <span>Categorias</span>
  <% end %>
  </li>
  <li class="nav-item">
    <%= link_to backoffice_admins_path, class: "nav-link" do %>
      <i class="fas fa-users fa-chart-area"></i>
      <span>Administradores</span>
    <% end %>
  </li>
</ul>

app/views/layouts/backoffice_shared/_topbar.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark static-top">

  <%= link_to "aoMercado", backoffice_path, class: "navbar-brand mr-1" %>

  <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
    <i class="fas fa-bars"></i>
  </button>

  <!-- User profile image -->
  <div class="ml-auto mr-0 mr-md-3 my-2 my-md-0">
    User photo
  </div>

  <!-- Navbar -->
  <ul class="navbar-nav ml-auto ml-md-0">
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-bell fa-fw"></i>
        <span class="badge badge-danger">9+</span>
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Something else here</a>
      </div>
    </li>
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-envelope fa-fw"></i>
        <span class="badge badge-danger">7</span>
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Something else here</a>
      </div>
    </li>
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-user-circle fa-fw"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
        <a class="dropdown-item" href="#">Settings</a>
        <a class="dropdown-item" href="#">Activity Log</a>
        <div class="dropdown-divider"></div>
        <!-- <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a> -->
        <%= link_to "Logout", destroy_admin_session_path, class: "dropdown-item" ,method: :delete %>
      </div>
    </li>
  </ul>

</nav>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html lang="pt-PT">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">

  <title>aoMercado | Site</title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="description" content="Mini loja virtual, um projecto do curso completo de Ruby on Rails">
  <meta name="keywords" content="mercado, virtual, online, compras, pagamentos, loja, e-commerce"/>
  <meta name="robots" content="index, follow">
  <meta name="author" content="Nelson Mfinda">
  <meta name="theme-color" content="#FFFFFF">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    'site', media: 'all', 'data-turbolinks-track': 'reload' %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'site', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <%= render partial: "layouts/site_shared/navigation" %>
  <%= yield %>
  <%= render partial: "layouts/site_shared/footer" %>
</body>
</html>

app/views/layouts/site_shared/_footer.html.erb
<!-- Footer -->
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; aoMercado 2019</p>
  </div>
  <!-- /.container -->
</footer>

app/views/layouts/site_shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="/">aoMercado {:}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Sobre</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Publicar anuncio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Entrar</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/members/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/members/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>